name: Check Formatting

on:
  push:
  pull_request:
jobs:
  format_check:
    runs-on: ubuntu-20.04
    env:
      CLANG_FORMAT: /usr/bin/clang-format-12
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install packages
        run: |
          sudo apt-get -y update
          sudo apt-get -y install clang-format-12 colordiff
      - name: precheck
        run: |
          pwd
          git --version
          git status
          git show --stat
          git show --stat HEAD~
      - name: check formatting pull request
        if: github.event_name == 'pull_request'
        run: |
          echo "Running formatting check against ${{ github.base_ref }}"
          ${{ github.workspace }}/.github/scripts/apply-format.sh ${{ github.base_ref }} --
      - name: check formatting push
        if: github.event_name == 'push'
        run: |
          ${{ github.workspace }}/.github/scripts/apply-format.sh HEAD~ --
